# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # ActivityType - The type of activity
    class ActivityType < T::Enum
      enums do
        NOTE = new('NOTE')
        EMAIL = new('EMAIL')
        OTHER = new('OTHER')
      end
    end

  end
end
