# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # CollectionType - The type of the collection. Authorized values are either PROJECT or LIST 
    class CollectionType < T::Enum
      enums do
        PROJECT = new('PROJECT')
        LIST = new('LIST')
      end
    end

  end
end
