# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class CreateProjectDto < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The user ID
      field :id_user, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id_user') } }
      # The name of the project
      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
      # The organization ID
      field :id_organization, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id_organization') } }


      sig { params(id_user: ::String, name: ::String, id_organization: T.nilable(::String)).void }
      def initialize(id_user: nil, name: nil, id_organization: nil)
        @id_user = id_user
        @name = name
        @id_organization = id_organization
      end
    end
  end
end
