# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class CustomFieldCreateDtoObjectTypeOwner < T::Enum
      enums do
        COMPANY = new('company')
        CONTACT = new('contact')
        DEAL = new('deal')
        LEAD = new('lead')
        NOTE = new('note')
        TASK = new('task')
        ENGAGEMENT = new('engagement')
        STAGE = new('stage')
        USER = new('user')
      end
    end
  end
end
