# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # CustomFieldResponseDataType - Attribute Data Type
    class CustomFieldResponseDataType < T::Enum
      enums do
        STRING = new('string')
        NUMBER = new('number')
      end
    end
  end
end
