# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # CustomFieldCreateDtoDataType - The data type of the custom field
    class CustomFieldCreateDtoDataType < T::Enum
      enums do
        STRING = new('string')
        NUMBER = new('number')
      end
    end

  end
end
