# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class DeductionItem < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The amount of company deduction
      field :company_deduction, T.nilable(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('company_deduction') } }
      # The amount of employee deduction
      field :employee_deduction, T.nilable(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('employee_deduction') } }
      # The name of the deduction
      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }


      sig { params(company_deduction: T.nilable(::Float), employee_deduction: T.nilable(::Float), name: T.nilable(::String)).void }
      def initialize(company_deduction: nil, employee_deduction: nil, name: nil)
        @company_deduction = company_deduction
        @employee_deduction = employee_deduction
        @name = name
      end
    end
  end
end
