# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # Direction - The direction of the engagement. Authorized values are INBOUND or OUTBOUND
    class Direction < T::Enum
      enums do
        INBOUND = new('INBOUND')
        OUTBOUND = new('OUTBOUND')
      end
    end

  end
end
