# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # EventResponseType - Scope of the event
    class EventResponseType < T::Enum
      enums do
        CRM_CONTACT_CREATED = new('crm.contact.created')
        CRM_CONTACT_PULLED = new('crm.contact.pulled')
        CRM_COMPANY_CREATED = new('crm.company.created')
        CRM_COMPANY_PULLED = new('crm.company.pulled')
        CRM_DEAL_CREATED = new('crm.deal.created')
        CRM_DEAL_PULLED = new('crm.deal.pulled')
        CRM_ENGAGEMENT_CREATED = new('crm.engagement.created')
        CRM_ENGAGEMENT_PULLED = new('crm.engagement.pulled')
        CRM_NOTE_CREATED = new('crm.note.created')
        CRM_NOTE_PULLED = new('crm.note.pulled')
        CRM_STAGE_PULLED = new('crm.stage.pulled')
        CRM_TASK_PULLED = new('crm.task.pulled')
        CRM_TASK_CREATED = new('crm.task.created')
        CRM_USER_PULLED = new('crm.user.pulled')
        TICKETING_TICKET_CREATED = new('ticketing.ticket.created')
        TICKETING_TICKET_PULLED = new('ticketing.ticket.pulled')
        TICKETING_COMMENT_CREATED = new('ticketing.comment.created')
        TICKETING_COMMENT_PULLED = new('ticketing.comment.pulled')
        TICKETING_ATTACHMENT_CREATED = new('ticketing.attachment.created')
        TICKETING_ATTACHMENT_PULLED = new('ticketing.attachment.pulled')
        TICKETING_COLLECTION_PULLED = new('ticketing.collection.pulled')
        TICKETING_ACCOUNT_PULLED = new('ticketing.account.pulled')
        TICKETING_CONTACT_PULLED = new('ticketing.contact.pulled')
        TICKETING_TAG_PULLED = new('ticketing.tag.pulled')
        TICKETING_TEAM_PULLED = new('ticketing.team.pulled')
        TICKETING_USER_PULLED = new('ticketing.user.pulled')
        ATS_ACTIVITY_CREATED = new('ats.activity.created')
        ATS_ACTIVITY_PULLED = new('ats.activity.pulled')
        ATS_APPLICATION_CREATED = new('ats.application.created')
        ATS_APPLICATION_PULLED = new('ats.application.pulled')
        ATS_ATTACHMENT_CREATED = new('ats.attachment.created')
        ATS_ATTACHMENT_PULLED = new('ats.attachment.pulled')
        ATS_CANDIDATE_CREATED = new('ats.candidate.created')
        ATS_CANDIDATE_PULLED = new('ats.candidate.pulled')
        ATS_DEPARTMENT_PULLED = new('ats.department.pulled')
        ATS_EECOS_PULLED = new('ats.eecos.pulled')
        ATS_INTERVIEW_CREATED = new('ats.interview.created')
        ATS_INTERVIEW_PULLED = new('ats.interview.pulled')
        ATS_JOB_PULLED = new('ats.job.pulled')
        ATS_JOBINTERVIEWSTAGE_PULLED = new('ats.jobinterviewstage.pulled')
        ATS_OFFER_CREATED = new('ats.offer.created')
        ATS_OFFICE_PULLED = new('ats.office.pulled')
        ATS_REJECTREASON_PULLED = new('ats.rejectreason.pulled')
        ATS_SCORECARD_PULLED = new('ats.scorecard.pulled')
        ATS_TAG_PULLED = new('ats.tag.pulled')
        ATS_USER_PULLED = new('ats.user.pulled')
        FILESTORAGE_FILE_CREATED = new('filestorage.file.created')
        FILESTORAGE_FILE_PULLED = new('filestorage.file.pulled')
        FILESTORAGE_FOLDER_CREATED = new('filestorage.folder.created')
        FILESTORAGE_FOLDER_PULLED = new('filestorage.folder.pulled')
        FILESTORAGE_GROUP_PULLED = new('filestorage.group.pulled')
        FILESTORAGE_USER_PULLED = new('filestorage.user.pulled')
        FILESTORAGE_DRIVE_PULLED = new('filestorage.drive.pulled')
        FILESTORAGE_PERMISSION_PULLED = new('filestorage.permission.pulled')
        FILESTORAGE_SHAREDLINK_PULLED = new('filestorage.sharedlink.pulled')
        CONNECTION_CREATED = new('connection.created')
      end
    end

  end
end
