# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class LinkedUserResponse < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :alias_, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('alias') } }

      field :id_linked_user, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id_linked_user') } }

      field :id_project, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id_project') } }

      field :linked_user_origin_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('linked_user_origin_id') } }


      sig { params(alias_: ::String, id_linked_user: ::String, id_project: ::String, linked_user_origin_id: ::String).void }
      def initialize(alias_: nil, id_linked_user: nil, id_project: nil, linked_user_origin_id: nil)
        @alias_ = alias_
        @id_linked_user = id_linked_user
        @id_project = id_project
        @linked_user_origin_id = linked_user_origin_id
      end
    end
  end
end
