# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class MapFieldToProviderDto < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :attribute_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('attributeId') } }

      field :linked_user_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('linked_user_id') } }

      field :source_custom_field_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('source_custom_field_id') } }

      field :source_provider, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('source_provider') } }


      sig { params(attribute_id: ::String, linked_user_id: ::String, source_custom_field_id: ::String, source_provider: ::String).void }
      def initialize(attribute_id: nil, linked_user_id: nil, source_custom_field_id: nil, source_provider: nil)
        @attribute_id = attribute_id
        @linked_user_id = linked_user_id
        @source_custom_field_id = source_custom_field_id
        @source_provider = source_provider
      end
    end
  end
end
