# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class Method < T::Enum
      enums do
        GET = new('GET')
        POST = new('POST')
        PATCH = new('PATCH')
        DELETE = new('DELETE')
        PUT = new('PUT')
      end
    end

  end
end
