# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # The modified date of the object
    class ModifiedAt < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig



      
      def initialize; end
    end
  end
end
