# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # OwnerType - The owner type of an email
    class OwnerType < T::Enum
      enums do
        COMPANY = new('COMPANY')
        CONTACT = new('CONTACT')
      end
    end

  end
end
