# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # PhoneType - The phone type. Authorized values are either MOBILE or WORK
    class PhoneType < T::Enum
      enums do
        MOBILE = new('MOBILE')
        WORK = new('WORK')
      end
    end

  end
end
