# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # Race - The race of the candidate
    class Race < T::Enum
      enums do
        AMERICAN_INDIAN_OR_ALASKAN_NATIVE = new('AMERICAN_INDIAN_OR_ALASKAN_NATIVE')
        ASIAN = new('ASIAN')
        BLACK_OR_AFRICAN_AMERICAN = new('BLACK_OR_AFRICAN_AMERICAN')
        HISPANIC_OR_LATINO = new('HISPANIC_OR_LATINO')
        WHITE = new('WHITE')
        NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER = new('NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER')
        TWO_OR_MORE_RACES = new('TWO_OR_MORE_RACES')
        DECLINE_TO_SELF_IDENTIFY = new('DECLINE_TO_SELF_IDENTIFY')
      end
    end

  end
end
