# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class ResyncStatusDto < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :provider, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('provider') } }

      field :status, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status') } }

      field :timestamp, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('timestamp'), 'decoder': Utils.datetime_from_iso_format(false) } }

      field :vertical, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('vertical') } }


      sig { params(provider: ::String, status: ::String, timestamp: ::DateTime, vertical: ::String).void }
      def initialize(provider: nil, status: nil, timestamp: nil, vertical: nil)
        @provider = provider
        @status = status
        @timestamp = timestamp
        @vertical = vertical
      end
    end
  end
end
