# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class ResyncStatusDtoStatus < T::Enum
      enums do
        SUCCESS = new('success')
        FAIL = new('fail')
      end
    end

  end
end
