# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class Security < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :bearer, ::String, { 'security': { 'scheme': true, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' } }


      sig { params(bearer: ::String).void }
      def initialize(bearer: nil)
        @bearer = bearer
      end
    end
  end
end
