# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class SignatureVerificationDto < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The payload event of the webhook.
      field :payload, ::OpenApiSDK::Shared::Payload, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('payload') } }
      # The secret of the webhook.
      field :secret, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('secret') } }
      # The signature of the webhook.
      field :signature, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('signature') } }


      sig { params(payload: ::OpenApiSDK::Shared::Payload, secret: ::String, signature: ::String).void }
      def initialize(payload: nil, secret: nil, signature: nil)
        @payload = payload
        @secret = secret
        @signature = signature
      end
    end
  end
end
