# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # TokenType - Strategy type
    class TokenType < T::Enum
      enums do
        OAUTH2 = new('oauth2')
        APIKEY = new('apikey')
        BASIC = new('basic')
      end
    end
  end
end
