# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedAtsApplicationOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::OpenApiSDK::Shared::UnifiedAtsApplicationOutputCreatedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :field_mappings, ::OpenApiSDK::Shared::UnifiedAtsApplicationOutputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }

      field :modified_at, ::OpenApiSDK::Shared::UnifiedAtsApplicationOutputModifiedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at') } }

      field :remote_data, ::OpenApiSDK::Shared::UnifiedAtsApplicationOutputRemoteData, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The application date
      field :applied_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('applied_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The UUID of the candidate
      field :candidate_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('candidate_id') } }
      # The UUID of the person credited for the application
      field :credited_to, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('credited_to') } }
      # The UUID of the current stage of the application
      field :current_stage, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('current_stage') } }
      # The UUID of the application
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The UUID of the job
      field :job_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('job_id') } }
      # The offers UUIDs for the application
      field :offers, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('offers') } }
      # The rejection reason for the application
      field :reject_reason, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('reject_reason') } }
      # The rejection date
      field :rejected_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('rejected_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The remote ID of the application in the context of the 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }
      # The source of the application
      field :source, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('source') } }


      sig { params(created_at: ::OpenApiSDK::Shared::UnifiedAtsApplicationOutputCreatedAt, field_mappings: ::OpenApiSDK::Shared::UnifiedAtsApplicationOutputFieldMappings, modified_at: ::OpenApiSDK::Shared::UnifiedAtsApplicationOutputModifiedAt, remote_data: ::OpenApiSDK::Shared::UnifiedAtsApplicationOutputRemoteData, applied_at: T.nilable(::DateTime), candidate_id: T.nilable(::String), credited_to: T.nilable(::String), current_stage: T.nilable(::String), id: T.nilable(::String), job_id: T.nilable(::String), offers: T.nilable(T::Array[::String]), reject_reason: T.nilable(::String), rejected_at: T.nilable(::DateTime), remote_id: T.nilable(::String), source: T.nilable(::String)).void }
      def initialize(created_at: nil, field_mappings: nil, modified_at: nil, remote_data: nil, applied_at: nil, candidate_id: nil, credited_to: nil, current_stage: nil, id: nil, job_id: nil, offers: nil, reject_reason: nil, rejected_at: nil, remote_id: nil, source: nil)
        @created_at = created_at
        @field_mappings = field_mappings
        @modified_at = modified_at
        @remote_data = remote_data
        @applied_at = applied_at
        @candidate_id = candidate_id
        @credited_to = credited_to
        @current_stage = current_stage
        @id = id
        @job_id = job_id
        @offers = offers
        @reject_reason = reject_reason
        @rejected_at = rejected_at
        @remote_id = remote_id
        @source = source
      end
    end
  end
end
