# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedEcommerceFulfillmentOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The carrier of the fulfilment
      field :carrier, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('carrier') } }
      # The created date of the object
      field :created_at, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }
      # The custom field mappings of the object between the remote 3rd party & Panora
      field :field_mappings, T.nilable(::OpenApiSDK::Shared::UnifiedEcommerceFulfillmentOutputFieldMappings), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }
      # The UUID of the fulfilment
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The items in the fulfilment
      field :items, T.nilable(::OpenApiSDK::Shared::UnifiedEcommerceFulfillmentOutputItems), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('items') } }
      # The modified date of the object
      field :modified_at, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at') } }
      # The UUID of the order associated with the fulfilment
      field :order_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('order_id') } }
      # The remote data of the customer in the context of the 3rd Party
      field :remote_data, T.nilable(::OpenApiSDK::Shared::UnifiedEcommerceFulfillmentOutputRemoteData), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The remote ID of the fulfilment in the context of the 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }
      # The tracking numbers of the fulfilment
      field :tracking_numbers, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tracking_numbers') } }
      # The tracking URLs of the fulfilment
      field :tracking_urls, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tracking_urls') } }


      sig { params(carrier: T.nilable(::String), created_at: T.nilable(::String), field_mappings: T.nilable(::OpenApiSDK::Shared::UnifiedEcommerceFulfillmentOutputFieldMappings), id: T.nilable(::String), items: T.nilable(::OpenApiSDK::Shared::UnifiedEcommerceFulfillmentOutputItems), modified_at: T.nilable(::String), order_id: T.nilable(::String), remote_data: T.nilable(::OpenApiSDK::Shared::UnifiedEcommerceFulfillmentOutputRemoteData), remote_id: T.nilable(::String), tracking_numbers: T.nilable(T::Array[::String]), tracking_urls: T.nilable(T::Array[::String])).void }
      def initialize(carrier: nil, created_at: nil, field_mappings: nil, id: nil, items: nil, modified_at: nil, order_id: nil, remote_data: nil, remote_id: nil, tracking_numbers: nil, tracking_urls: nil)
        @carrier = carrier
        @created_at = created_at
        @field_mappings = field_mappings
        @id = id
        @items = items
        @modified_at = modified_at
        @order_id = order_id
        @remote_data = remote_data
        @remote_id = remote_id
        @tracking_numbers = tracking_numbers
        @tracking_urls = tracking_urls
      end
    end
  end
end
