# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedTicketingAttachmentOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::OpenApiSDK::Shared::UnifiedTicketingAttachmentOutputCreatedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :field_mappings, ::OpenApiSDK::Shared::UnifiedTicketingAttachmentOutputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }
      # The file name of the attachment
      field :file_name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_name') } }
      # The file url of the attachment
      field :file_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_url') } }

      field :modified_at, ::OpenApiSDK::Shared::UnifiedTicketingAttachmentOutputModifiedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at') } }

      field :remote_data, ::OpenApiSDK::Shared::UnifiedTicketingAttachmentOutputRemoteData, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The uploader's UUID of the attachment
      field :uploader, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('uploader') } }
      # The UUID of the comment the attachment is tied to
      field :comment_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('comment_id') } }
      # The UUID of the attachment
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The id of the attachment in the context of the 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }
      # The UUID of the ticket the attachment is tied to
      field :ticket_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('ticket_id') } }


      sig { params(created_at: ::OpenApiSDK::Shared::UnifiedTicketingAttachmentOutputCreatedAt, field_mappings: ::OpenApiSDK::Shared::UnifiedTicketingAttachmentOutputFieldMappings, file_name: ::String, file_url: ::String, modified_at: ::OpenApiSDK::Shared::UnifiedTicketingAttachmentOutputModifiedAt, remote_data: ::OpenApiSDK::Shared::UnifiedTicketingAttachmentOutputRemoteData, uploader: ::String, comment_id: T.nilable(::String), id: T.nilable(::String), remote_id: T.nilable(::String), ticket_id: T.nilable(::String)).void }
      def initialize(created_at: nil, field_mappings: nil, file_name: nil, file_url: nil, modified_at: nil, remote_data: nil, uploader: nil, comment_id: nil, id: nil, remote_id: nil, ticket_id: nil)
        @created_at = created_at
        @field_mappings = field_mappings
        @file_name = file_name
        @file_url = file_url
        @modified_at = modified_at
        @remote_data = remote_data
        @uploader = uploader
        @comment_id = comment_id
        @id = id
        @remote_id = remote_id
        @ticket_id = ticket_id
      end
    end
  end
end
