# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # UnifiedCrmEngagementOutputType - The type of the engagement. Authorized values are EMAIL, CALL or MEETING
    class UnifiedCrmEngagementOutputType < T::Enum
      enums do
        EMAIL = new('EMAIL')
        CALL = new('CALL')
        MEETING = new('MEETING')
      end
    end

  end
end
