# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedFilestorageFileInput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The url of the file
      field :file_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_url') } }
      # The UUID of the folder tied to the file
      field :folder_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('folder_id') } }
      # The mime type of the file
      field :mime_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('mime_type') } }
      # The name of the file
      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
      # The UUID of the permission tied to the file
      field :permission, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('permission') } }
      # The UUID of the shared link tied to the file
      field :shared_link, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('shared_link') } }
      # The size of the file
      field :size, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('size') } }
      # The custom field mappings of the object between the remote 3rd party & Panora
      field :field_mappings, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }


      sig { params(file_url: ::String, folder_id: ::String, mime_type: ::String, name: ::String, permission: ::String, shared_link: ::String, size: ::String, field_mappings: T.nilable(T::Hash[Symbol, ::Object])).void }
      def initialize(file_url: nil, folder_id: nil, mime_type: nil, name: nil, permission: nil, shared_link: nil, size: nil, field_mappings: nil)
        @file_url = file_url
        @folder_id = folder_id
        @mime_type = mime_type
        @name = name
        @permission = permission
        @shared_link = shared_link
        @size = size
        @field_mappings = field_mappings
      end
    end
  end
end
