# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedTicketingAccountOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::OpenApiSDK::Shared::UnifiedTicketingAccountOutputCreatedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :field_mappings, ::OpenApiSDK::Shared::UnifiedTicketingAccountOutputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }

      field :modified_at, ::OpenApiSDK::Shared::UnifiedTicketingAccountOutputModifiedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at') } }
      # The name of the account
      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

      field :remote_data, ::OpenApiSDK::Shared::UnifiedTicketingAccountOutputRemoteData, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The domains of the account
      field :domains, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('domains') } }
      # The UUID of the account
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The id of the account in the context of the 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }


      sig { params(created_at: ::OpenApiSDK::Shared::UnifiedTicketingAccountOutputCreatedAt, field_mappings: ::OpenApiSDK::Shared::UnifiedTicketingAccountOutputFieldMappings, modified_at: ::OpenApiSDK::Shared::UnifiedTicketingAccountOutputModifiedAt, name: ::String, remote_data: ::OpenApiSDK::Shared::UnifiedTicketingAccountOutputRemoteData, domains: T.nilable(T::Array[::String]), id: T.nilable(::String), remote_id: T.nilable(::String)).void }
      def initialize(created_at: nil, field_mappings: nil, modified_at: nil, name: nil, remote_data: nil, domains: nil, id: nil, remote_id: nil)
        @created_at = created_at
        @field_mappings = field_mappings
        @modified_at = modified_at
        @name = name
        @remote_data = remote_data
        @domains = domains
        @id = id
        @remote_id = remote_id
      end
    end
  end
end
