# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # UnifiedAtsActivityInputVisibility - The visibility of the activity
    class UnifiedAtsActivityInputVisibility < T::Enum
      enums do
        ADMIN_ONLY = new('ADMIN_ONLY')
        PUBLIC = new('PUBLIC')
        PRIVATE = new('PRIVATE')
      end
    end

  end
end
