# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # UnifiedTicketingTicketInputPriority - The priority of the ticket. Authorized values are HIGH, MEDIUM or LOW.
    class UnifiedTicketingTicketInputPriority < T::Enum
      enums do
        HIGH = new('HIGH')
        MEDIUM = new('MEDIUM')
        LOW = new('LOW')
      end
    end

  end
end
