# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedFilestorageFolderInput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The description of the folder
      field :description, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }
      # The UUID of the drive tied to the folder
      field :drive_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('drive_id') } }

      field :field_mappings, ::OpenApiSDK::Shared::UnifiedFilestorageFolderInputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }
      # The url of the folder
      field :folder_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('folder_url') } }
      # The name of the folder
      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
      # The UUID of the parent folder
      field :parent_folder_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('parent_folder_id') } }
      # The UUID of the permission tied to the folder
      field :permission, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('permission') } }
      # The UUID of the shared link tied to the folder
      field :shared_link, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('shared_link') } }
      # The size of the folder
      field :size, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('size') } }


      sig { params(description: ::String, drive_id: ::String, field_mappings: ::OpenApiSDK::Shared::UnifiedFilestorageFolderInputFieldMappings, folder_url: ::String, name: ::String, parent_folder_id: ::String, permission: ::String, shared_link: ::String, size: ::String).void }
      def initialize(description: nil, drive_id: nil, field_mappings: nil, folder_url: nil, name: nil, parent_folder_id: nil, permission: nil, shared_link: nil, size: nil)
        @description = description
        @drive_id = drive_id
        @field_mappings = field_mappings
        @folder_url = folder_url
        @name = name
        @parent_folder_id = parent_folder_id
        @permission = permission
        @shared_link = shared_link
        @size = size
      end
    end
  end
end
