# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # UnifiedCrmTaskOutputStatus - The status of the task. Authorized values are PENDING, COMPLETED.
    class UnifiedCrmTaskOutputStatus < T::Enum
      enums do
        PENDING = new('PENDING')
        COMPLETED = new('COMPLETED')
      end
    end

  end
end
