# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # The remote data of the tracking category in the context of the 3rd Party
    class UnifiedAccountingTrackingcategoryOutputRemoteData < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig



      
      def initialize; end
    end
  end
end
