# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # UnifiedTicketingTicketInputCreatorType - The creator type of the comment. Authorized values are either USER or CONTACT
    class UnifiedTicketingTicketInputCreatorType < T::Enum
      enums do
        USER = new('USER')
        CONTACT = new('CONTACT')
      end
    end

  end
end
