# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedCrmUserOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::OpenApiSDK::Shared::UnifiedCrmUserOutputCreatedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }
      # The email of the user
      field :email, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }

      field :field_mappings, ::OpenApiSDK::Shared::UnifiedCrmUserOutputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }

      field :modified_at, ::OpenApiSDK::Shared::UnifiedCrmUserOutputModifiedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at') } }
      # The name of the user
      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

      field :remote_data, ::OpenApiSDK::Shared::UnifiedCrmUserOutputRemoteData, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The UUID of the user
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The id of the user in the context of the Crm 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }


      sig { params(created_at: ::OpenApiSDK::Shared::UnifiedCrmUserOutputCreatedAt, email: ::String, field_mappings: ::OpenApiSDK::Shared::UnifiedCrmUserOutputFieldMappings, modified_at: ::OpenApiSDK::Shared::UnifiedCrmUserOutputModifiedAt, name: ::String, remote_data: ::OpenApiSDK::Shared::UnifiedCrmUserOutputRemoteData, id: T.nilable(::String), remote_id: T.nilable(::String)).void }
      def initialize(created_at: nil, email: nil, field_mappings: nil, modified_at: nil, name: nil, remote_data: nil, id: nil, remote_id: nil)
        @created_at = created_at
        @email = email
        @field_mappings = field_mappings
        @modified_at = modified_at
        @name = name
        @remote_data = remote_data
        @id = id
        @remote_id = remote_id
      end
    end
  end
end
