# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # The custom field mappings of the object between the remote 3rd party & Panora
    class UnifiedAccountingContactOutputFieldMappings < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig



      
      def initialize; end
    end
  end
end
