# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedAtsAttachmentInput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :field_mappings, ::OpenApiSDK::Shared::UnifiedAtsAttachmentInputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }
      # The type of the file
      field :attachment_type, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('attachment_type') } }
      # The UUID of the candidate
      field :candidate_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('candidate_id') } }
      # The name of the file
      field :file_name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_name') } }
      # The URL of the file
      field :file_url, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_url') } }
      # The remote creation date of the attachment
      field :remote_created_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The remote modification date of the attachment
      field :remote_modified_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_modified_at'), 'decoder': Utils.datetime_from_iso_format(true) } }


      sig { params(field_mappings: ::OpenApiSDK::Shared::UnifiedAtsAttachmentInputFieldMappings, attachment_type: T.nilable(::String), candidate_id: T.nilable(::String), file_name: T.nilable(::String), file_url: T.nilable(::String), remote_created_at: T.nilable(::DateTime), remote_modified_at: T.nilable(::DateTime)).void }
      def initialize(field_mappings: nil, attachment_type: nil, candidate_id: nil, file_name: nil, file_url: nil, remote_created_at: nil, remote_modified_at: nil)
        @field_mappings = field_mappings
        @attachment_type = attachment_type
        @candidate_id = candidate_id
        @file_name = file_name
        @file_url = file_url
        @remote_created_at = remote_created_at
        @remote_modified_at = remote_modified_at
      end
    end
  end
end
