# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedAtsEeocsOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The UUID of the candidate
      field :candidate_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('candidate_id') } }
      # The created date of the object
      field :created_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The disability status of the candidate
      field :disability_status, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('disability_status') } }
      # The custom field mappings of the object between the remote 3rd party & Panora
      field :field_mappings, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }
      # The gender of the candidate
      field :gender, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('gender') } }
      # The UUID of the EEOC
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The modified date of the object
      field :modified_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The race of the candidate
      field :race, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('race') } }
      # The remote data of the EEOC in the context of the 3rd Party
      field :remote_data, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The remote ID of the EEOC in the context of the 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }
      # The submission date of the EEOC
      field :submitted_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('submitted_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The veteran status of the candidate
      field :veteran_status, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('veteran_status') } }


      sig { params(candidate_id: T.nilable(::String), created_at: T.nilable(::DateTime), disability_status: T.nilable(::String), field_mappings: T.nilable(T::Hash[Symbol, ::Object]), gender: T.nilable(::String), id: T.nilable(::String), modified_at: T.nilable(::DateTime), race: T.nilable(::String), remote_data: T.nilable(T::Hash[Symbol, ::Object]), remote_id: T.nilable(::String), submitted_at: T.nilable(::DateTime), veteran_status: T.nilable(::String)).void }
      def initialize(candidate_id: nil, created_at: nil, disability_status: nil, field_mappings: nil, gender: nil, id: nil, modified_at: nil, race: nil, remote_data: nil, remote_id: nil, submitted_at: nil, veteran_status: nil)
        @candidate_id = candidate_id
        @created_at = created_at
        @disability_status = disability_status
        @field_mappings = field_mappings
        @gender = gender
        @id = id
        @modified_at = modified_at
        @race = race
        @remote_data = remote_data
        @remote_id = remote_id
        @submitted_at = submitted_at
        @veteran_status = veteran_status
      end
    end
  end
end
