# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # UnifiedAtsJobOutputStatus - The status of the job
    class UnifiedAtsJobOutputStatus < T::Enum
      enums do
        OPEN = new('OPEN')
        CLOSED = new('CLOSED')
        DRAFT = new('DRAFT')
        ARCHIVED = new('ARCHIVED')
        PENDING = new('PENDING')
      end
    end

  end
end
