# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedFilestorageGroupOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::OpenApiSDK::Shared::UnifiedFilestorageGroupOutputCreatedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :field_mappings, ::OpenApiSDK::Shared::UnifiedFilestorageGroupOutputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }

      field :modified_at, ::OpenApiSDK::Shared::UnifiedFilestorageGroupOutputModifiedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at') } }
      # The name of the group
      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

      field :remote_data, ::OpenApiSDK::Shared::UnifiedFilestorageGroupOutputRemoteData, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # Indicates whether or not this object has been deleted in the third party platform.
      field :remote_was_deleted, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_was_deleted') } }
      # Uuids of users of the group
      field :users, T::Array[::String], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('users') } }
      # The UUID of the group
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The id of the group in the context of the 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }


      sig { params(created_at: ::OpenApiSDK::Shared::UnifiedFilestorageGroupOutputCreatedAt, field_mappings: ::OpenApiSDK::Shared::UnifiedFilestorageGroupOutputFieldMappings, modified_at: ::OpenApiSDK::Shared::UnifiedFilestorageGroupOutputModifiedAt, name: ::String, remote_data: ::OpenApiSDK::Shared::UnifiedFilestorageGroupOutputRemoteData, remote_was_deleted: T::Boolean, users: T::Array[::String], id: T.nilable(::String), remote_id: T.nilable(::String)).void }
      def initialize(created_at: nil, field_mappings: nil, modified_at: nil, name: nil, remote_data: nil, remote_was_deleted: nil, users: nil, id: nil, remote_id: nil)
        @created_at = created_at
        @field_mappings = field_mappings
        @modified_at = modified_at
        @name = name
        @remote_data = remote_data
        @remote_was_deleted = remote_was_deleted
        @users = users
        @id = id
        @remote_id = remote_id
      end
    end
  end
end
