# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedAtsAttachmentOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::OpenApiSDK::Shared::UnifiedAtsAttachmentOutputCreatedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :field_mappings, ::OpenApiSDK::Shared::UnifiedAtsAttachmentOutputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }

      field :modified_at, ::OpenApiSDK::Shared::UnifiedAtsAttachmentOutputModifiedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at') } }

      field :remote_data, ::OpenApiSDK::Shared::UnifiedAtsAttachmentOutputRemoteData, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The type of the file
      field :attachment_type, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('attachment_type') } }
      # The UUID of the candidate
      field :candidate_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('candidate_id') } }
      # The name of the file
      field :file_name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_name') } }
      # The URL of the file
      field :file_url, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('file_url') } }
      # The UUID of the attachment
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The remote creation date of the attachment
      field :remote_created_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The remote ID of the attachment
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }
      # The remote modification date of the attachment
      field :remote_modified_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_modified_at'), 'decoder': Utils.datetime_from_iso_format(true) } }


      sig { params(created_at: ::OpenApiSDK::Shared::UnifiedAtsAttachmentOutputCreatedAt, field_mappings: ::OpenApiSDK::Shared::UnifiedAtsAttachmentOutputFieldMappings, modified_at: ::OpenApiSDK::Shared::UnifiedAtsAttachmentOutputModifiedAt, remote_data: ::OpenApiSDK::Shared::UnifiedAtsAttachmentOutputRemoteData, attachment_type: T.nilable(::String), candidate_id: T.nilable(::String), file_name: T.nilable(::String), file_url: T.nilable(::String), id: T.nilable(::String), remote_created_at: T.nilable(::DateTime), remote_id: T.nilable(::String), remote_modified_at: T.nilable(::DateTime)).void }
      def initialize(created_at: nil, field_mappings: nil, modified_at: nil, remote_data: nil, attachment_type: nil, candidate_id: nil, file_name: nil, file_url: nil, id: nil, remote_created_at: nil, remote_id: nil, remote_modified_at: nil)
        @created_at = created_at
        @field_mappings = field_mappings
        @modified_at = modified_at
        @remote_data = remote_data
        @attachment_type = attachment_type
        @candidate_id = candidate_id
        @file_name = file_name
        @file_url = file_url
        @id = id
        @remote_created_at = remote_created_at
        @remote_id = remote_id
        @remote_modified_at = remote_modified_at
      end
    end
  end
end
