# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedAtsOfferOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :created_at, ::OpenApiSDK::Shared::UnifiedAtsOfferOutputCreatedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at') } }

      field :field_mappings, ::OpenApiSDK::Shared::UnifiedAtsOfferOutputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }

      field :modified_at, ::OpenApiSDK::Shared::UnifiedAtsOfferOutputModifiedAt, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at') } }

      field :remote_data, ::OpenApiSDK::Shared::UnifiedAtsOfferOutputRemoteData, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The UUID of the application
      field :application_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('application_id') } }
      # The closing date of the offer
      field :closed_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('closed_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The UUID of the creator
      field :created_by, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_by') } }
      # The UUID of the offer
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The remote creation date of the offer
      field :remote_created_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The remote ID of the offer in the context of the 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }
      # The sending date of the offer
      field :sent_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sent_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The start date of the offer
      field :start_date, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('start_date'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The status of the offer
      field :status, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status') } }


      sig { params(created_at: ::OpenApiSDK::Shared::UnifiedAtsOfferOutputCreatedAt, field_mappings: ::OpenApiSDK::Shared::UnifiedAtsOfferOutputFieldMappings, modified_at: ::OpenApiSDK::Shared::UnifiedAtsOfferOutputModifiedAt, remote_data: ::OpenApiSDK::Shared::UnifiedAtsOfferOutputRemoteData, application_id: T.nilable(::String), closed_at: T.nilable(::DateTime), created_by: T.nilable(::String), id: T.nilable(::String), remote_created_at: T.nilable(::DateTime), remote_id: T.nilable(::String), sent_at: T.nilable(::DateTime), start_date: T.nilable(::DateTime), status: T.nilable(::String)).void }
      def initialize(created_at: nil, field_mappings: nil, modified_at: nil, remote_data: nil, application_id: nil, closed_at: nil, created_by: nil, id: nil, remote_created_at: nil, remote_id: nil, sent_at: nil, start_date: nil, status: nil)
        @created_at = created_at
        @field_mappings = field_mappings
        @modified_at = modified_at
        @remote_data = remote_data
        @application_id = application_id
        @closed_at = closed_at
        @created_by = created_by
        @id = id
        @remote_created_at = remote_created_at
        @remote_id = remote_id
        @sent_at = sent_at
        @start_date = start_date
        @status = status
      end
    end
  end
end
