# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedCrmTaskOutput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The content of the task
      field :content, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('content') } }
      # The status of the task. Authorized values are PENDING, COMPLETED.
      field :status, ::OpenApiSDK::Shared::UnifiedCrmTaskOutputStatus, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Shared::UnifiedCrmTaskOutputStatus, false) } }
      # The subject of the task
      field :subject, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('subject') } }
      # The UUID of the company tied to the task
      field :company_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('company_id') } }
      # The created date of the object
      field :created_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The UUID of the deal tied to the task
      field :deal_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('deal_id') } }
      # The due date of the task
      field :due_date, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('due_date') } }
      # The custom field mappings of the task between the remote 3rd party & Panora
      field :field_mappings, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }
      # The finished date of the task
      field :finished_date, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('finished_date') } }
      # The UUID of the task
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }
      # The modified date of the object
      field :modified_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('modified_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The remote data of the task in the context of the Crm 3rd Party
      field :remote_data, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_data') } }
      # The ID of the task in the context of the Crm 3rd Party
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_id') } }
      # The UUID of the user tied to the task
      field :user_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user_id') } }


      sig { params(content: ::String, status: ::OpenApiSDK::Shared::UnifiedCrmTaskOutputStatus, subject: ::String, company_id: T.nilable(::String), created_at: T.nilable(::DateTime), deal_id: T.nilable(::String), due_date: T.nilable(::String), field_mappings: T.nilable(T::Hash[Symbol, ::Object]), finished_date: T.nilable(::String), id: T.nilable(::String), modified_at: T.nilable(::DateTime), remote_data: T.nilable(T::Hash[Symbol, ::Object]), remote_id: T.nilable(::String), user_id: T.nilable(::String)).void }
      def initialize(content: nil, status: nil, subject: nil, company_id: nil, created_at: nil, deal_id: nil, due_date: nil, field_mappings: nil, finished_date: nil, id: nil, modified_at: nil, remote_data: nil, remote_id: nil, user_id: nil)
        @content = content
        @status = status
        @subject = subject
        @company_id = company_id
        @created_at = created_at
        @deal_id = deal_id
        @due_date = due_date
        @field_mappings = field_mappings
        @finished_date = finished_date
        @id = id
        @modified_at = modified_at
        @remote_data = remote_data
        @remote_id = remote_id
        @user_id = user_id
      end
    end
  end
end
