# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedAtsActivityInput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The type of activity
      field :activity_type, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('activity_type') } }
      # The body of the activity
      field :body, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('body') } }
      # The UUID of the candidate
      field :candidate_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('candidate_id') } }
      # The custom field mappings of the object between the remote 3rd party & Panora
      field :field_mappings, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }
      # The remote creation date of the activity
      field :remote_created_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('remote_created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # The subject of the activity
      field :subject, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('subject') } }
      # The visibility of the activity
      field :visibility, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('visibility') } }


      sig { params(activity_type: T.nilable(::String), body: T.nilable(::String), candidate_id: T.nilable(::String), field_mappings: T.nilable(T::Hash[Symbol, ::Object]), remote_created_at: T.nilable(::DateTime), subject: T.nilable(::String), visibility: T.nilable(::String)).void }
      def initialize(activity_type: nil, body: nil, candidate_id: nil, field_mappings: nil, remote_created_at: nil, subject: nil, visibility: nil)
        @activity_type = activity_type
        @body = body
        @candidate_id = candidate_id
        @field_mappings = field_mappings
        @remote_created_at = remote_created_at
        @subject = subject
        @visibility = visibility
      end
    end
  end
end
