# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class UnifiedCrmCompanyInput < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :field_mappings, ::OpenApiSDK::Shared::UnifiedCrmCompanyInputFieldMappings, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('field_mappings') } }
      # The name of the company
      field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
      # The addresses of the company
      field :addresses, T.nilable(T::Array[::OpenApiSDK::Shared::Address]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('addresses') } }
      # The email addresses of the company
      field :email_addresses, T.nilable(T::Array[::OpenApiSDK::Shared::Email]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email_addresses') } }
      # The industry of the company. Authorized values can be found in the Industry enum.
      field :industry, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('industry') } }
      # The number of employees of the company
      field :number_of_employees, T.nilable(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('number_of_employees') } }
      # The phone numbers of the company
      field :phone_numbers, T.nilable(T::Array[::OpenApiSDK::Shared::Phone]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('phone_numbers') } }
      # The UUID of the user who owns the company
      field :user_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('user_id') } }


      sig { params(field_mappings: ::OpenApiSDK::Shared::UnifiedCrmCompanyInputFieldMappings, name: ::String, addresses: T.nilable(T::Array[::OpenApiSDK::Shared::Address]), email_addresses: T.nilable(T::Array[::OpenApiSDK::Shared::Email]), industry: T.nilable(::String), number_of_employees: T.nilable(::Float), phone_numbers: T.nilable(T::Array[::OpenApiSDK::Shared::Phone]), user_id: T.nilable(::String)).void }
      def initialize(field_mappings: nil, name: nil, addresses: nil, email_addresses: nil, industry: nil, number_of_employees: nil, phone_numbers: nil, user_id: nil)
        @field_mappings = field_mappings
        @name = name
        @addresses = addresses
        @email_addresses = email_addresses
        @industry = industry
        @number_of_employees = number_of_employees
        @phone_numbers = phone_numbers
        @user_id = user_id
      end
    end
  end
end
