# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class Url < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The url.
      field :url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('url') } }
      # The url type. It takes [WEBSITE | BLOG | LINKEDIN | GITHUB | OTHER]
      field :url_type, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('url_type') } }


      sig { params(url: ::String, url_type: ::String).void }
      def initialize(url: nil, url_type: nil)
        @url = url
        @url_type = url_type
      end
    end
  end
end
