# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class Vertical < T::Enum
      enums do
        TICKETING = new('ticketing')
        ATS = new('ats')
        ACCOUNTING = new('accounting')
        HRIS = new('hris')
        CRM = new('crm')
        FILESTORAGE = new('filestorage')
        ECOMMERCE = new('ecommerce')
        MARKETINGAUTOMATION = new('marketingautomation')
      end
    end

  end
end
