# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class WebhookDto < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The description of the webhook.
      field :description, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }
      # The events that the webhook listen to.
      field :scope, T::Array[::String], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('scope') } }
      # The endpoint url of the webhook.
      field :url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('url') } }


      sig { params(description: ::String, scope: T::Array[::String], url: ::String).void }
      def initialize(description: nil, scope: nil, url: nil)
        @description = description
        @scope = scope
        @url = url
      end
    end
  end
end
