# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class CreateAccountingAccountRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :unified_accounting_account_input, ::OpenApiSDK::Shared::UnifiedAccountingAccountInput, { 'request': { 'media_type': 'application/json' } }
      # The connection token
      field :x_connection_token, ::String, { 'header': { 'field_name': 'x-connection-token', 'style': 'simple', 'explode': false } }
      # Set to true to include data from the original Accounting software.
      field :remote_data, T.nilable(T::Boolean), { 'query_param': { 'field_name': 'remote_data', 'style': 'form', 'explode': true } }


      sig { params(unified_accounting_account_input: ::OpenApiSDK::Shared::UnifiedAccountingAccountInput, x_connection_token: ::String, remote_data: T.nilable(T::Boolean)).void }
      def initialize(unified_accounting_account_input: nil, x_connection_token: nil, remote_data: nil)
        @unified_accounting_account_input = unified_accounting_account_input
        @x_connection_token = x_connection_token
        @remote_data = remote_data
      end
    end
  end
end
