# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetProjectsResponse < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer

      field :project_responses, T.nilable(T::Array[::OpenApiSDK::Shared::ProjectResponse])


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, project_responses: T.nilable(T::Array[::OpenApiSDK::Shared::ProjectResponse])).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, project_responses: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @project_responses = project_responses
      end
    end
  end
end
