# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetRetriedRequestResponseRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # id of the retryJob returned when you initiated a passthrough request.
      field :retry_id, ::String, { 'path_param': { 'field_name': 'retryId', 'style': 'simple', 'explode': false } }


      sig { params(retry_id: ::String).void }
      def initialize(retry_id: nil)
        @retry_id = retry_id
      end
    end
  end
end
