# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class QueryRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :query_body, ::OpenApiSDK::Shared::QueryBody, { 'request': { 'media_type': 'application/json' } }
      # The connection token
      field :x_connection_token, ::String, { 'header': { 'field_name': 'x-connection-token', 'style': 'simple', 'explode': false } }


      sig { params(query_body: ::OpenApiSDK::Shared::QueryBody, x_connection_token: ::String).void }
      def initialize(query_body: nil, x_connection_token: nil)
        @query_body = query_body
        @x_connection_token = x_connection_token
      end
    end
  end
end
