# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class StatusRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :vertical, ::String, { 'path_param': { 'field_name': 'vertical', 'style': 'simple', 'explode': false } }


      sig { params(vertical: ::String).void }
      def initialize(vertical: nil)
        @vertical = vertical
      end
    end
  end
end
