# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class VerifyEventResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # Dynamic event payload
      field :data, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('data') } }


      sig { params(data: T.nilable(T::Hash[Symbol, ::Object])).void }
      def initialize(data: nil)
        @data = data
      end
    end
  end
end
